// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "modelConfigMode": string;
      "apiConfigMode": string;
      "provider": string;
      "timeoutSeconds": number;
      "usePDFAsInputSource": boolean;
      "usePDFAnnotationsAsContext": boolean;
      "importPDFAnnotationsAsField": boolean;
      "enablePDFInputTruncation": boolean;
      "pdfTextMaxChars": number;
      "pdfAnnotationTextMaxChars": number;
      "customPromptTemplate": string;
      "customFolderSummaryPromptTemplate": string;
    };
  }
}
